// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPGCoolGuy.Models;

#nullable disable

namespace RPGCoolGuy.Migrations
{
    [DbContext(typeof(CharacterContext))]
    partial class CharacterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RPGCoolGuy.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Attack")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Defense")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("HP")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 20,
                            Defense = 20,
                            HP = 20,
                            Name = "Dave"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 30,
                            Defense = 30,
                            HP = 30,
                            Name = "Tony"
                        },
                        new
                        {
                            Id = 3,
                            Attack = 99,
                            Defense = 99,
                            HP = 9999,
                            Name = "Peter Griffin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
